import numpy as np
import os
import sys
import argparse


# Column names of the per-tissue *_bootstrap_summary.txt files generated by run_ld_corr.py
output_names = ['calibration_slope', 'per_snp_eqtl_h2', 'borzoi_variance', 'unstandardized_borzoi_variance', 'correlation']


def extract_ld_corr_output_files(ld_corr_output_file_list):
	# Load list of per-tissue ld-corr *_bootstrap_summary.txt files (one file per line)
	ld_corr_output_files = []
	with open(ld_corr_output_file_list) as f:
		for line in f:
			line = line.rstrip()
			if line == '':
				continue
			if not os.path.isfile(line):
				raise ValueError('Per-tissue ld-corr output file does not exist: ' + line)
			ld_corr_output_files.append(line)
	if len(ld_corr_output_files) == 0:
		raise ValueError('No per-tissue ld-corr output files found in ' + ld_corr_output_file_list)
	return ld_corr_output_files


def get_reference_anno_category(anno_name, category_name, annotation_version):
	# For a given cell, return the (annotation_name, category_name) of the intercept cell its
	# estimates should be differenced against, or None if the cell has no intercept reference
	# (it IS an intercept cell, or -- in the magnitude stratified version -- it is a magnitude
	# dependent annotation left unstratified and so has no per-strata intercept).
	if annotation_version == 'default':
		# A single global intercept
		if anno_name == 'intercept':
			return None
		return ('intercept', 'intercept')

	if annotation_version == 'magnitude_stratified':
		# The intercept is stratified by borzoi magnitude bin. Magnitude stratified categories are
		# named 'magnitude_bin<m>X<base_category>', and the intercept for magnitude bin <m> is the
		# cell 'borzoi_magnitude_stratifiedXintercept':'magnitude_bin<m>Xintercept'. Cells with no
		# 'magnitude_bin<m>X' prefix (magnitude dependent annotations left unstratified) are skipped.
		if anno_name == 'borzoi_magnitude_stratifiedXintercept':
			return None
		if not category_name.startswith('magnitude_bin') or 'X' not in category_name:
			return None
		magnitude_bin_prefix = category_name.split('X')[0]
		return ('borzoi_magnitude_stratifiedXintercept', magnitude_bin_prefix + 'Xintercept')

	raise ValueError('Unknown annotation version: ' + annotation_version)


def load_single_tissue_summary(summary_file):
	# Reorganize a per-tissue *_bootstrap_summary.txt file into per-cell estimates.
	# Returns:
	#   cell_to_observed: (anno_name, category_name) -> observed estimate vector
	#   cell_to_bootstrap: (anno_name, category_name) -> {sample_iter -> estimate vector}
	#   ordered_cells: list of (anno_name, category_name) in the order they appear
	cell_to_observed = {}
	cell_to_bootstrap = {}
	ordered_cells = []
	observed_cells = {}

	head_count = 0
	with open(summary_file) as f:
		for line in f:
			line = line.rstrip()
			data = line.split('\t')
			if head_count == 0:
				head_count = head_count + 1
				expected_header = ['annotation_name', 'category_name', 'sample_label', 'sample_iter'] + output_names
				if data != expected_header:
					raise ValueError('Unexpected header in ' + summary_file + '. Expected:\n' + '\t'.join(expected_header))
				continue
			anno_name = data[0]
			category_name = data[1]
			sample_label = data[2]
			sample_iter = data[3]
			estimates = np.asarray(data[4:]).astype(float)

			cell = (anno_name, category_name)
			if cell not in observed_cells:
				observed_cells[cell] = 1
				ordered_cells.append(cell)
				cell_to_bootstrap[cell] = {}

			if sample_label == 'observed':
				cell_to_observed[cell] = estimates
			elif sample_label == 'bootstrap':
				cell_to_bootstrap[cell][sample_iter] = estimates
			else:
				raise ValueError('Unknown sample_label ' + sample_label + ' in ' + summary_file)

	return cell_to_observed, cell_to_bootstrap, ordered_cells


def meta_analyze_cells(per_tissue_observed, per_tissue_bootstrap, ordered_cells):
	# Average each cell's estimates across tissues, separately for the observed estimate and for
	# each (shared) bootstrap iteration. Bootstrap iteration <b> uses the same resampled gene set in
	# every tissue, so tissues can be averaged within an iteration to preserve the pairing needed for
	# a valid difference. Cells missing in a tissue are simply averaged over the tissues that have them.
	meta_observed = {}
	meta_bootstrap = {}
	for cell in ordered_cells:
		observed_estimates = [per_tissue[cell] for per_tissue in per_tissue_observed if cell in per_tissue]
		if len(observed_estimates) > 0:
			meta_observed[cell] = np.nanmean(np.asarray(observed_estimates), axis=0)

		meta_bootstrap[cell] = {}
		bootstrap_iters = {}
		for per_tissue in per_tissue_bootstrap:
			if cell in per_tissue:
				for sample_iter in per_tissue[cell]:
					bootstrap_iters[sample_iter] = 1
		for sample_iter in bootstrap_iters:
			iter_estimates = [per_tissue[cell][sample_iter] for per_tissue in per_tissue_bootstrap if cell in per_tissue and sample_iter in per_tissue[cell]]
			meta_bootstrap[cell][sample_iter] = np.nanmean(np.asarray(iter_estimates), axis=0)

	return meta_observed, meta_bootstrap


def compute_intercept_difference_stats(cell_to_observed, cell_to_bootstrap, ordered_cells, annotation_version):
	# For every cell that has an intercept reference, difference its estimates from the intercept's
	# estimates -- paired within each bootstrap iteration -- and summarize the difference for each
	# output variable. Returns a list of output rows.
	difference_rows = []
	for cell in ordered_cells:
		anno_name, category_name = cell
		reference_cell = get_reference_anno_category(anno_name, category_name, annotation_version)
		if reference_cell is None:
			continue
		if cell not in cell_to_observed:
			continue
		if reference_cell not in cell_to_observed:
			print('WARNING: intercept reference ' + str(reference_cell) + ' not found for cell ' + str(cell) + '; skipping')
			continue

		observed_difference = cell_to_observed[cell] - cell_to_observed[reference_cell]

		# Paired bootstrap differences (only iterations present for both the cell and its intercept)
		cell_bootstrap = cell_to_bootstrap[cell]
		reference_bootstrap = cell_to_bootstrap[reference_cell]
		shared_iters = [sample_iter for sample_iter in cell_bootstrap if sample_iter in reference_bootstrap]
		if len(shared_iters) > 0:
			bootstrap_differences = np.asarray([cell_bootstrap[sample_iter] - reference_bootstrap[sample_iter] for sample_iter in shared_iters])
		else:
			bootstrap_differences = np.zeros((0, len(output_names)))

		for output_iter, output_name in enumerate(output_names):
			observed_value = observed_difference[output_iter]

			bootstrap_distribution = bootstrap_differences[:, output_iter]
			bootstrap_distribution = bootstrap_distribution[np.isfinite(bootstrap_distribution)]

			if len(bootstrap_distribution) < 2:
				bootstrap_mean = np.nan
				bootstrap_se = np.nan
				gaussian_z_score = np.nan
				empirical_ci = [np.nan, np.nan]
			else:
				bootstrap_mean = np.mean(bootstrap_distribution)
				bootstrap_se = np.std(bootstrap_distribution, ddof=1)
				if bootstrap_se == 0.0:
					gaussian_z_score = np.nan
				else:
					gaussian_z_score = observed_value/bootstrap_se
				empirical_ci = np.quantile(bootstrap_distribution, [.025, .975])

			difference_rows.append((anno_name, category_name, reference_cell[1], output_name, observed_value, bootstrap_mean, bootstrap_se, gaussian_z_score, empirical_ci[0], empirical_ci[1]))

	return difference_rows


def write_difference_stats(output_file, difference_rows):
	with open(output_file, 'w') as t:
		t.write('annotation_name\tcategory_name\treference_category_name\toutput_name\tdifference\tbootstrapped_mean_difference\tdifference_se\tgaussian_z_score\tempirical_ci_lower\tempirical_ci_upper\n')
		for difference_row in difference_rows:
			t.write('\t'.join([str(field) for field in difference_row]) + '\n')
	print(output_file)


#######################
# Command line args
#######################
parser = argparse.ArgumentParser()
parser.add_argument('--ld-corr-output-file-list', dest='ld_corr_output_file_list', default='None', type=str, help='File containing one per-tissue ld-corr *_bootstrap_summary.txt file per line')
parser.add_argument('--meta-analyzed-output-stem', dest='meta_analyzed_output_stem', default='None', type=str, help='Output file stem for the cross-tissue meta-analyzed intercept-difference results')
parser.add_argument('--annotation-version', dest='annotation_version', default='default', type=str, choices=['default', 'magnitude_stratified'], help='Which annotation version these results are from. Determines the intercept each cell is differenced against: a single global intercept (default), or the per-magnitude-bin intercept (magnitude_stratified).')
args = parser.parse_args()

ld_corr_output_file_list = args.ld_corr_output_file_list
meta_analyzed_output_stem = args.meta_analyzed_output_stem
annotation_version = args.annotation_version


##############################
# Load per-tissue results, and write a per-tissue intercept-difference stats file for each
##############################
ld_corr_output_files = extract_ld_corr_output_files(ld_corr_output_file_list)
print('Computing intercept differences (' + annotation_version + ') for ' + str(len(ld_corr_output_files)) + ' per-tissue ld-corr result files')

per_tissue_observed = []
per_tissue_bootstrap = []
ordered_cells = None
for ld_corr_output_file in ld_corr_output_files:
	cell_to_observed, cell_to_bootstrap, file_ordered_cells = load_single_tissue_summary(ld_corr_output_file)
	per_tissue_observed.append(cell_to_observed)
	per_tissue_bootstrap.append(cell_to_bootstrap)
	# Use the cell ordering from the first file for the meta-analyzed output
	if ordered_cells is None:
		ordered_cells = file_ordered_cells

	# Per-tissue intercept-difference stats (written alongside the per-tissue summary file)
	if not ld_corr_output_file.endswith('_bootstrap_summary.txt'):
		raise ValueError('Expected per-tissue file to end with _bootstrap_summary.txt: ' + ld_corr_output_file)
	per_tissue_output_file = ld_corr_output_file[:-len('_bootstrap_summary.txt')] + '_intercept_diff_stats.txt'
	per_tissue_difference_rows = compute_intercept_difference_stats(cell_to_observed, cell_to_bootstrap, file_ordered_cells, annotation_version)
	write_difference_stats(per_tissue_output_file, per_tissue_difference_rows)


##############################
# Meta-analyze across tissues, then write the cross-tissue intercept-difference stats file
##############################
meta_observed, meta_bootstrap = meta_analyze_cells(per_tissue_observed, per_tissue_bootstrap, ordered_cells)
meta_difference_rows = compute_intercept_difference_stats(meta_observed, meta_bootstrap, ordered_cells, annotation_version)
write_difference_stats(meta_analyzed_output_stem + '_intercept_diff_stats.txt', meta_difference_rows)
